### ISSUE TITLE
[BUG] Nick podendo ser registrado duas vezes

### ISSUE THREAD

**Issue by gurodrigues-dev** [gurodrigues-dev/to-do-flask#1]
@vmartinsz responsavel pela resolução

**Comment by vmartinsz** [comment]
Resolvido aqui -> https://github.com/gurodrigues-dev/to-do-flask/pull/3

**Comment by vmartinsz** [comment]
Resolvido aqui -> https://github.com/gurodrigues-dev/to-do-flask/pull/3
